# Permalinks
permalink: pretty

# Server
exclude: [".gitignore", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.md", "sass", "script"]

# Meta
og:
  image: /assets/img/logo.jpg
  title: Medufy
  url: http://medufy.com/
  description: Medufy provides you independent medical education based on your needs. Save time money and lives with our  digital learning platform.

site_url: ../../
